version: '3.8'

services:
  web:
    build: .
    container_name: php-apache-web

    ports:
      - "8200:80"  # Map localhost:8200 to container's port 80

    volumes:
      - .:/var/www/html  # Sync the project files to the container

    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data

    networks:
      - app-network

  db:
    build: ../database/impl # Use your custom Dockerfile for PostgreSQL
    container_name: postgres-db
    restart: always
    
    ports:
      - "8432:5432"  # Map localhost:8432 to container's port 5432

    volumes:
      - db_data:/var/lib/postgresql/data  # Persist the database data

    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
